### ISSUE TITLE
Apart from views and Duration implement fuzzy match too

### ISSUE THREAD

**Issue by voidash** [couldbejake/spotify2mp3#1]
Hello, I like the idea of using spotify metadata to search for video on Youtube. Really neat concept. But it would be awesome if you add in fuzzy match too apart from duration and views constraint. You search for a spotify music title, if the first result video title and spotify video title fuzzy matches with more than 60% then download it, that way we can set duration and views won't matter. 

Here is the tutorial that might help you. 
https://towardsdatascience.com/fuzzy-string-matching-in-python-68f240d910fe

also it would be great if you use command line argument parser instead of using console input. Look into `argparse`

**Comment by couldbejake** [comment]
Interesting, I've not heard of fuzzy match before, but I'm thinking about first searching explicitly for an audio only version of the song, fuzzy matching will help.

Tomorrow I will also add command line input and may also implement an option to download all playlists of a given user.

Thank you for the suggestions!

**Comment by couldbejake** [comment]
This feature is pending,
