### ISSUE TITLE
fail log

### ISSUE THREAD

**Issue by robotsheepboy** [couldbejake/spotify2mp3#11]
Got an error and it asked me to post it here

[failed_log.txt](https://github.com/couldbejake/spotify2mp3/files/8792243/failed_log.txt)

**Comment by couldbejake** [comment]
It looks like you tried downloading a video that was age restricted. I'll look into patching that as soon as possible.

**Comment by couldbejake** [comment]
@robotsheepboy I've added a temporary patch to skip age restricted songs. I will also submit an issue to pytube (which downloads the songs), and ask for this to be patched.

Additionally you may want to check updated to the main spotify2mp3 page if you are planning on downloading songs today.

**Comment by annieoxe** [comment]
Hi, I have been using your tool a time, but today I was trying to download a playlist and and all the songs have age restrictions. I tryied with multiple playlist and all gets the same result... Songs that 100% don't have age restriction and previosly been downloaded.

**Comment by couldbejake** [comment]
We can fix this by switching to https://github.com/yt-dlp/yt-dlp. I will add this feature soon, else feel free to add it yourself!

**Comment by couldbejake** [comment]
https://stackoverflow.com/questions/73088233/python-youtube-dl-does-not-allow-to-download-age-restricted-videos#answers
