### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by leunamnauj** [couldbejake/spotify2mp3#2]
Any reason for not having a requirements.txt?

This is the one I've created as part of the install process
`beautifulsoup4==4.11.1
bs4==0.0.1
certifi==2021.10.8
charset-normalizer==2.0.12
coverage==5.5
decorator==4.4.2
deprecation==2.1.0
eyed3==0.9.6
filetype==1.0.13
idna==3.3
imageio==2.19.2
imageio-ffmpeg==0.4.7
moviepy==1.0.3
numpy==1.22.3
packaging==21.3
Pillow==9.1.1
proglog==0.1.10
pyparsing==3.0.9
pytube==12.1.0
requests==2.27.1
soupsieve==2.3.2.post1
toml==0.10.2
tqdm==4.64.0
urllib3==1.26.9
youtube-search==2.1.0
`

**Comment by couldbejake** [comment]
Oops, I forgot to create one,

If you don't mind I'll create a requirements.txt with the list you've just posted.

Thank you,
Jake

**Comment by couldbejake** [comment]
@leunamnauj the packages you've specified don't seem to be compatible,
Do you mind letting me know what version of Python you're using?

**Comment by leunamnauj** [comment]
Python3.8

**Comment by couldbejake** [comment]
@leunamnauj Looks good, installation is flawless although in the future may add support for different Python versions.
