### ISSUE TITLE
Not work on Android with Termux

### ISSUE THREAD

**Issue by bremaya** [couldbejake/spotify2mp3#22]
I received this error

ModuleNotFoundError: No module named 'requests'

**Comment by couldbejake** [comment]
Did you do the following from the readme?

⚙️ Installation

Go to the project directory

$ cd spotify2mp3

Install desired packages using PIP 3.8

$ pip3.8 install -r requirements.txt

I can look into supporting termux on Android but will need to do more research into how to install packages

**Comment by bremaya** [comment]
Ok man I solved this. Thanks for the support.

Em sex., 25 de nov. de 2022 17:49, Jake Nelson ***@***.***>
escreveu:

**Comment by couldbejake** [comment]
How did you solve it?

**Comment by bremaya** [comment]
I simply installed the dependency with python

Em sex., 25 de nov. de 2022 17:51, Jake Nelson ***@***.***>
escreveu:
