### ISSUE TITLE
for only one specific song downloader what to use

### ISSUE THREAD

**Issue by DhavalDobariya333** [couldbejake/spotify2mp3#23]

**Comment by couldbejake** [comment]
Hi, sorry for the delay. We have plans to expand this to allow for the download of single songs, as well as albums.

Single songs

For the moment, add the single song to a playlist, and then download the playlist.

Albums

For album downloads, copy all songs of the album into a playlist

**Comment by DhavalDobariya333** [comment]
Thanks for suggestions

Do you have any idea how we can do it, 
Please give little suggestions on that
so I can help you to build it...

**Comment by couldbejake** [comment]
Hi Dhaval, as you can see on [line 137](https://github.com/couldbejake/spotify2mp3/blob/main/run.py#L137), the songs are enumerated over, it's just a matter of separating these out into functions.

I have plans to expand this tool to allow for the feature you have just requested, as well as the ability to download albums, but I have not had the time and I have noticed interest in this project slowing.

Using the code on line 137, you need to add and copy the following;

1) (optional) Look up information about the song on Spotify to get the artist and album cover.
2) Create a search string for looking the song up on YouTube (line 137).
3) Download the song from YouTube, and optionally add the artist and album cover -> save as mp3.

Let me know if you need any more help, I will accept your PR once complete.

Thanks,
Jake

**Comment by couldbejake** [comment]
Hi @DhavalDobariya333.

I'm just wondering whether you made any progress, as I plan to implement this feature today.

Thanks!

**Comment by DhavalDobariya333** [comment]
Okay you do it.

**Comment by ImAccia** [comment]
> Hi, sorry for the delay. We have plans to expand this to allow for the download of single songs, as well as albums.
> 
> Single songs
> 
> For the moment, add the single song to a playlist, and then download the playlist.
> 
> Albums
> 
> For album downloads, copy all songs of the album into a playlist

If ur interested i just forked ur project and made some modifications, it can currently download albums as well.
The code isn't very clean because I made it quickly.
You can now also use it as a webservice if you want, i implemented it in a webservice using Flask, pretty easy to do.

If u need any help with album/single song downloads hmu, it isn't hard at all

**Comment by couldbejake** [comment]
LGTM!

Hi @ImAccia,

Doesn't look too bad at all. Thank you for your work!
If you'd like to submit a pull request, I'll be happy to accept it.

My apologies to everyone using this project as I've been pretty busy lately.

We still have more to come, and will strongly consider packaging this application into an executable with a user interface in a future update.

Thanks!

**Comment by ImAccia** [comment]
> LGTM!
> 
> Hi @ImAccia,
> 
> Doesn't look too bad at all. Thank you for your work! If you'd like to submit a pull request, I'll be happy to accept it.
> 
> My apologies to everyone using this project as I've been pretty busy lately.
> 
> We still have more to come, and will strongly consider packaging this application into an executable with a user interface in a future update.
> 
> Thanks!

Just opened a pull req

**Comment by ImAccia** [comment]
UPDATE

Just commited on my fork with single song downloads enables, simply send a link of a song to start downloading it

**Comment by couldbejake** [comment]
@DhavalDobariya333 patch #28 should now fix your issue.
