### ISSUE TITLE
Single Song

### ISSUE THREAD

**Issue by theDvrkWolf** [couldbejake/spotify2mp3#24]
While im adding a single song in my playlist and trying to download it, it downloads another song from the album putting the name of the song that i was about to download. Why?

Example:

Link => A-song
Downloaded Song => audio[B-song] with name[A-song]

**Comment by couldbejake** [comment]
Does this occur with other songs, or only a once? Do you think you could so send a link to the playlist, thanks!

**Comment by theDvrkWolf** [comment]
It happens with this album: https://open.spotify.com/album/2HWRfJI3aMCrIQEiQFVuhq?si=UysbZ1Z8SluuClBUR_mpKA

**Comment by theDvrkWolf** [comment]
And yeah it occur with other songs too.

**Comment by theDvrkWolf** [comment]
![Welcome - Spotify-mp3 - Visual Studio Code 26_02_2023 16_00_27](https://user-images.githubusercontent.com/79983011/221415164-ed5ed3f4-3cab-4067-beec-09b832a44e1e.png)

**Comment by theDvrkWolf** [comment]
i want the BUGGATI but it downloads Ekali with BUGGATI name.

**Comment by couldbejake** [comment]
@theDvrkWolf How are you managing to enter that link? This tool does not currently support the downloading of albums, but I can add this functionality today.

**Comment by theDvrkWolf** [comment]
Im downloading them from my playlist where I add them. I just showed you the album of the songs that i got.

**Comment by theDvrkWolf** [comment]
Add a feature to download the song from the url of the track not the playlist..

**Comment by couldbejake** [comment]
Yep, I have the same issue now, let me have a look into it for you.

**Comment by couldbejake** [comment]
This is due to the song not existing on YouTube, and seems to be a limitation of the application unfortunately.

I'm not sure why the artist would choose not to post on YouTube, as this application works by looking up the song name and artist on YouTube, there is currently no way using this script to download the song.

I apologise for the inconvience.

Jake
