### ISSUE TITLE
Parsing issue from html

### ISSUE THREAD

**Issue by rudramenaria** [couldbejake/spotify2mp3#25]
This is the Stack Trace of error

```
Traceback (most recent call last):
  File "run.py", line 296, in <module>
    main()
  File "run.py", line 281, in main
    playlist_name = html.fromstring(page.content).xpath('/html/body/div/div/div/div/div[1]/div/div[2]/h1')[0].text_content().strip()
IndexError: list index out of range
```

**Comment by couldbejake** [comment]
Hi @rudramenaria, do you think you could provide the playlist you are attempting to download, so I can receeate the bug?

Thanks,
Couldbejake

**Comment by rudramenaria** [comment]
actually i am getting issue in all the playlist

**Comment by couldbejake** [comment]
Hi Rudra, sorry for the delay! Looking into this now

**Comment by rudramenaria** [comment]
@couldbejake by the way i am also an Mobile Application Developer, lets catch up some time. i am working on a EDM music app, will show you.

**Comment by couldbejake** [comment]
Sounds interesting! Feel free to contact me via jake@couldbejake.io

**Comment by rudramenaria** [comment]
@couldbejake we can get on a meet sometime whenever you are free, this is my Whatsapp no: +91 9414551590, let me know whenever you are free.

**Comment by couldbejake** [comment]
Will do!

**Comment by couldbejake** [comment]
@rudramenaria does your issue still occur on the latest version? I feel as if this may be caused by a differing locales.

**Comment by couldbejake** [comment]
I seem to be able to run the code with your playlist successfully. If this issue still occurs, please either open another ticket, or contact me directly.

Thank you.
