### ISSUE TITLE
Index out of bounds error due to missing album cover

### ISSUE THREAD

**Issue by Unchain6787** [couldbejake/spotify2mp3#38]
First of all thank you very much for such an amazing tool, it has been a great help in preserving my collection.
I copied all my library into 100 song playlists for downloading, in order to stop using Spotify. Cheers.

Two of my songs are missing album art on Spotify, I'm not sure how that happened. I assume it broke some terms and so was removed by Spotify (because I know it is a requirement of submission). In any case, this caused a null exception which was easy enough to identify and remedy. Here is the exception for reference:

> Traceback (most recent call last):
  File "/home/anon/spotify2mp3/spotify2mp3.py", line 164, in <module>
    main(playlist=url, quality=quality, min_views=DEFAULT_MIN_VIEWS_FOR_DOWNLOAD, max_length=DEFAULT_MAX_LENGTH_FOR_DOWNLOAD)
  File "/home/anon/spotify2mp3/spotify2mp3.py", line 110, in main
    success =downloader.download_playlist(playlist)  
  File "/home/anon/spotify2mp3/downloader.py", line 75, in download_playlist
    self.prep_folder("downloads/playlists/" + playlist.get_title(True))
  File "/home/anon/spotify2mp3/apis/spotify.py", line 133, in get_title
    self.load_metadata()
  File "/home/anon/spotify2mp3/apis/spotify.py", line 113, in load_metadata
    this_track.load_metadata(track["track"])
  File "/home/anon/spotify2mp3/apis/spotify.py", line 304, in load_metadata
    "image_url": album_images[0].get("url", const.UNKNOWN_ALBUM_COVER_URL),
IndexError: list index out of range

**Comment by couldbejake** [comment]
Hi, not a problem I will update the code for you now

It looks like album_images has no child elements, we can instead ensure album_images exists and has items, else use const.UNKNOWN_ALBUM_COVER_URL, a question mark image.

**Comment by couldbejake** [comment]
Do you happen to have the song the program failed on?

**Comment by trevorobrecht** [comment]
It was "March of Death" by OBNX

**Comment by couldbejake** [comment]
Hi @Unchain6787 will be updating the program within the next 2 days, sorry for the delay, prior commitments!

**Comment by couldbejake** [comment]
The application has now been updated. The faulty check for an album cover should now be patched.

Please let me know if you experience any more issues.

Kind regards,
Jake!
