### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by utsavpaudel** [couldbejake/spotify2mp3#43]

**Comment by utsavpaudel** [comment]
Even tried in a clean env, looks like flask submodule error in flask\helpers.py line 14

**Comment by couldbejake** [comment]
Can you post a full error log? Also which Python version are you using?

**Comment by utsavpaudel** [comment]
Python version is 3.8.1 and I lost the error message now. It's solved by using flask 2.2.5. I already see a pull request there, approve it I guess.

**Comment by couldbejake** [comment]
Brilliant to hear it's solved.

I've just accepted the Synk PR.

Let me know if there's anything else you need.

Kind regards,
Jake
